language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

env:
  - BROWSER_NAME="firefox" PLATFORM="Linux"
  - BROWSER_NAME="chrome" PLATFORM="Linux"
  - BROWSER_NAME="ie" PLATFORM="Windows 10"

before_script:
  - npm run lint
  - sleep 15

script:
  - npm run test-cov
  - npm run test-e2e-saucelabs
  - npm run test-react

sudo: required

notifications:
  email:
    - jed@keystonejs.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
  sauce_connect: true
